services:
  - type: web
    name: money-manager-backend
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/money-manager-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql.railway.internal:3306/railway?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: vfzbaCNMzMeoLSCrLHBWUNhXLcyxHnqt
      - key: JWT_SECRET
        value: your_super_secret_key_that_should_be_long_and_secure_at_least_256bits
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: SERVER_PORT
        value: "8080"
      - key: SPRING_WEB_CORS_ALLOWED_ORIGINS
        value: "*"
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: "false"
